### ISSUE TITLE
Add NIR Spectral Standards Templates

### ISSUE THREAD

**Issue by elliesch** [BDNYC/UltracoolTypingKit#9]
This doesn't run without the NIR spectral standards templates for the full JHK spectrum (Table 9 in the paper.) Should I upload just those spectra here?

**Comment by kelle** [comment]
yes. the spectra of the NIR standards should totally be public ASAP.

**Comment by elliesch** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Upload NIR spectral standards to Github](https://trello.com/c/76ENhxRm/43-upload-nir-spectral-standards-to-github)

**Comment by elliesch** [comment]
5bf21ee944cb1308e7d861210bebac812bcad2be
